### ISSUE TITLE
Rename this library?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/IR-DirectFETs.pretty#2]
The "IR" in this library refers to International Rectifier. This company was [purchased by Infineon](https://www.infineon.com/cms/en/about-infineon/press/press-releases/2015/INFXX201501-020.html) some time ago, so it makes little sense to continue using "IR" in the library name.

Furthermore, IR wasn't the only company to release parts in a DirectFET package (before they were bought) so this package was never proprietary to International Rectifier.

Lastly, I believe we're moving towards library names which do not use vendor names.

For all those reasons, I propose we change the name of this library. Going to simply `DirectFETs` would be an option. However, since these are simply another package for FETs, would it make more sense to rename it to `Housings_DirectFET`? That would group these footprints with other libraries often also used for FETs (like SOIC8, though the TO/SOT are still alphabetically far away but still include "Housings" in their library name).

**Comment by poeschlr** [comment]
I would go for the Housings option.
I would go further and rename TO/SOT to include housing in their name as well.
(To be clear: mark old libs as deprecated and copy the contents to the new lib. Deleting libs creates problems in the stable release.)

**Comment by evanshultz** [comment]
I don't have authority (or I don't know that I do). @SchrodingersGat Can you re-name this repo to `Housings_DirectFET` when you return?

And how about `Housings_TO_SOT_THT` and `Housings_TO_SOT_SMD`? Kinda ugly and long, but it seems to me that's the best way to capture all the important information.

**Comment by SchrodingersGat** [comment]
There have been many people confused over the `Housings_` prefix, I personally don't really like it either.

If we are looking to rename other libs to `Conn_` perhaps this prefix could be dropped entirely? e.g. `QFN_`, `DirectFET_` etc

If we can arrive at a good solution for merging all the .pretty repos into a single repository, then we may as well put in the effort to address the naming schemes for the various libraries too.

**Comment by evanshultz** [comment]
Agreed. I don't like `Housings` either. I do like some grouping for typical IC packages, though. (And why I like a `Connector_` or `Conn_` prefix.) Mouser and Digi-Key both use `Package / Case`. Could we change all `Housings_` to `Package_` and then update this and the TO/SOT repos similarly?

Would your utility that searches the libraries for valid footprints help here? I'll be happy to put in the work of updating symbol libraries, for the greater good, if we have an automated way to figure out what needs updating.

**Comment by poeschlr** [comment]
I think this is again a change that should only happen for kicad v5 
(in other words: until v5 is out we might consider keeping the names as they are now. Deprecate the old libs once v5 comes out and move on to a better lib naming scheme.)

Also we should decide on a priority of things that need to be done for v5. In case we over strech our selves we should ensure that high priority stuff gets finished before something with a low priority is started.

**Comment by SchrodingersGat** [comment]
> Would your utility that searches the libraries for valid footprints help here? I'll be happy to put in the work of updating symbol libraries, for the greater good, if we have an automated way to figure out what needs updating.

Probably not as useful but the problem here is much easier. It's simply renaming a set of directories to another set of directories.

> I think this is again a change that should only happen for kicad v5

Absolutely.

> Also we should decide on a priority of things that need to be done for v5. In case we over strech our selves we should ensure that high priority stuff gets finished before something with a low priority is started.

Agreed

**Comment by evanshultz** [comment]
Anybody have an idea for a name that is better than `Housings`? `Package` is all I can come up with. It's an extremely common term, possibly the best term, and see how many times it's used at a reference site (not an authoritative one) like the Wikipedia page for SOIC: https://en.wikipedia.org/wiki/Small_Outline_Integrated_Circuit.

For a better datapoint, it's the only term I see Amkor using on their SOIC page (https://www.amkor.com/go/soic) and they manufacture IC packages. JEDEC also uses "package" for SOIC: https://www.jedec.org/taxonomy/term/2343.

What about beyond SOIC? Perhaps BGA. See JEDEC dictionary at https://www.jedec.org/standards-documents/dictionary/terms/ball-grid-array-bga and also https://www.jedec.org/standards-documents/dictionary/terms/package. Again, "package" seems the best (only?) appropriate term.

So... how about `Package_SOIC`, `Package_BGA`, `Package_DirectFET`, etc.? It doesn't roll off the tongue quite as well, but I think it's more accurate. Is that concise enough, because JEDEC is only focused on ICs while our library covers many types of electronic components? Does the word "Package" followed by the package type obviously communicate it's an IC package to the user?

BTW, I don't find any parts in transistors.lib that use any DirectFET footprints. So it may not break anything (but would still be a change) regardless of when we change this library name.

**Comment by SchrodingersGat** [comment]
I much prefer `Package`, however as the others are all (currently) `Housing` then I would prefer to maintain that naming convention (at least for now).

For the v5 changes we will rename to `Package` (or a better term if we come up with it).

Another option is just dropping the prefix entirely, e.g `SOIC`, `BGA`, `DirectFET` (etc)

**Comment by SchrodingersGat** [comment]
I'd like to close this out. As this is not really the same as an IC package, I am not sure we should have the `Package` prefix.

Is anyone against simply renaming this to `DirectFET`?

**Comment by evanshultz** [comment]
Here are a few links where the word "package" is used in relation to DirectFETs:
- https://www.infineon.com/cms/en/product/power/mosfet/20v-300v-n-channel-power-mosfet/optimos-and-strongirfet-latest-packages/directfet-microstencil/channel.html?channel=5546d462503812bb01504d3a0abf4175
- https://www.infineon.com/cms/en/about-infineon/press/market-news/2011/irf1449668558645.html
- https://www.infineon.com/dgdl/Infineon-AN-1035-AN-v29_00-EN.pdf?fileId=5546d462533600a40153559159020f76
- http://www.electronicdesign.com/boards/what-directfet-technology

I still feel "package" is the correct term. While currently there are only discrete transistors (which are actually an array of transistors) available in DirectFET, to my knowledge, there are also discrete transistors available in SOIC and SOT which are also associated with the term "package".

Furthermore, it would be possible to make an IC in DirectFET. Perhaps a driver and transistor combo. The substrate on the top must be bonded to the drain, but otherwise there could be any number of pins adjacent to the board. They only need to be masked by an interposer. The die need not contain just one transistor.

Since this isn't a bare die, there is some type of package. In a DirectFET the package is minimal (in number of steps, but quite complicated) compared with SOIC, but there still is a package. The package is a formed piece of metal and an interposer instead of a lead frame, bond wires, and a plastic molding, but it's still the die's package. In my opinion, anyway.

**Comment by SchrodingersGat** [comment]
Good enough for me. I'll rename and update the lib-tables
