### ISSUE TITLE
RFC: should the Names" footprints be removed? 

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/IR-DirectFETs.pretty#3]
Hey folks
I'm gonna overhaul this library in the near future since Im almost  finished with my directfet generator. The first thing that comes to mind is the duplicate footprint with GDS instead of 123. Isnt this an old and deprecated practise? And should they be deleted?

**Comment by evanshultz** [comment]
@Shackmeister 
That sounds great to me! I do believe you're correct that we only need numbers, not names.

Looking at https://github.com/KiCad/kicad-library/blob/master/library/transistors.lib, I don't find any symbols referencing these parts. I know they're not in ir.lib, either. So I don't see anything that would break if the footprints with named pads were removed.

Now that you've brought this up, I'd like to create symbols for all the Infineon DirectFETs so we have symbols in the library to use these footprints. Perhaps I can finish that in the next week or so.

**Comment by Shackmeister** [comment]
@evanshultz Thanks for the input :) sorry I havent looked at the Audio lib overhaul but to be honest Im kinda lost with symbols :) only made footprints and 3D models so far :)
